config/routes.rb
Rails.application.routes.draw do
  namespace :employer do
    get 'bookmarks/index'
  end
  namespace :employer do
    get 'application/index'
  end
  namespace :employer do
    get 'payment/new'
  end
  resources :news
  resources :places
  devise_for :users,
                path: '',
                path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
                controllers: {omniauth_callbacks: 'omniauth_callbacks' }
    as :user do
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
    end


    scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # mount Sidekiq::Web => "/sidekiq"

    get 'companies/show'
    mount Ckeditor::Engine => '/ckeditor'
    root to: 'static_pages#home'
    resources :jobs
    get 'users/new'
    get 'static_pages/home',to: "home#jobs"
    get '/home', to: 'static_pages#home'
    get '/contact', to: 'static_pages#contact'
    get '/all', to: 'static_pages#products'
    get 'search', to: 'search#index'
    namespace :admin do
      root "admin#index"
    end

    resources :jobs do
      resources :applyjobs, only: [:create, :destroy]
    end
    resources :jobs do
      resources :bookmarks, only: [:create, :destroy]
    end

    resources :jobs
    resources :cvs
    resources :companies, only: [:show]
    resources :profiles
    resources :experiences
    resources :rooms
    resources :companies do
      resources :jobs, only: [:index]
    end
    resources :educations
    resources :users do
      resources :applyjobs

    end

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

    resources :users do

      resources :bookmarks
    end

    resources :experiences
    resources :cv_skills
    resources :cv_languages
    namespace :employer do
      resources :jobs do
        resources :applyjobs
      end
      resources :jobs do
        resources :bookmarks
      end
      resources :profiles
      resources :webhooks
      resources :bookmarks, only: [:index]
      resources :companies
      resources :payments
      resources :applications, only: [:index]
      resources :members
      resources :users
      resources :portal_sessions, only: [:create]

    end
    resources :portfolios
    resources :search do
      collection do
        get :autocomplete
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @bookmark = Bookmark.new
    if params[:type] =="newest"|| params[:type].nil?
      @approvedJobs = Job.all.job_new.all_approved_true.page(params[:page]).per(10)
    elsif params[:type] =="recommended"
      @job_Recommended = Job.job_Recommended.job_salary.job_new.all_approved_true.page(params[:page]).per(10)
    end
    @job_slides = Job.job_slide.job_new
    @q = Job.ransack params[:q]
    @jobs = @q.result
    respond_to do |format|
      format.html
      format.json { render json: @jobs.limit(5) }
    end
  end

  def index
  end
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInLeft;">
				<li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
				<li class="active">Contact</li>
			</ol>
		</div>
	</div>
<div class="contact">
			<div class="container">
				<h3>Contact</h3>
				
				<div class="contact-grids">
					<div class="contact-form">
							<form action="#" method="post">
								<div class="contact-bottom">
									<div class="col-md-4 in-contact">
										<span>Name</span>
										<input type="text" name="name">
									</div>
									<div class="col-md-4 in-contact">
										<span>Email</span>
										<input type="text" name="email" >
									</div>
									<div class="col-md-4 in-contact">
										<span>Phonenumber</span>
										<input type="text" name="phonenumber">
									</div>
									<div class="clearfix"> </div>
								</div>
							
								<div class="contact-bottom-top">
									<span>Message</span>
									<textarea  name="message"> </textarea>								
									</div>
								<input type="submit" value="Send">
							</form>
						</div>
				<div class="address">
					<div class=" address-more">
						<h2>Address</h2>
						<div class="col-md-4 address-grid">
							<i class="glyphicon glyphicon-map-marker"></i>
							<div class="address1">
								<p>Lorem ipsum dolor</p>
								<p>TL 19034-88974</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="col-md-4 address-grid ">
							<i class="glyphicon glyphicon-phone"></i>
							<div class="address1">
								<p>+885699655</p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="col-md-4 address-grid ">
							<i class="glyphicon glyphicon-envelope"></i>
							<div class="address1">
								<p><a href="mailto:@example.com"> @example.com</a></p>
							</div>
							<div class="clearfix"> </div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
		</div>
	</div>
<!--//content-->
<!--map-->
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3279847.2716062404!2d145.46948275!3d-36.60289065!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad4314b7e18954f%3A0x5a4efce2be829534!2sVictoria%2C+Australia!5e0!3m2!1sen!2sin!4v1443674224626" width="100%" height="" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>

app/views/static_pages/home.html.erb
<div class="slider-123">
  <div class="slider center slider-user">
    <% if !@job_slides.nil? %>
      <% @job_slides.each do |job_slide|%>
        <div class="card mb-3 card-nen">
        <% if job_slide.images.attached? %>
            <%= link_to image_tag(job_slide.images, class: "post-img"),job_path(job_slide) %>
        <% else %>
          <%= link_to image_tag('no-image.jpg', class: "post-img"),job_path(job_slide)%>
        <% end %>
          <div class="card-body col-md-4 text-user">
            <h5 class="card-title card-text"><%= link_to job_slide.title,job_path(job_slide) %></h5>
            <p class="card-text"><%= link_to job_slide.user.company.full_name,company_path(job_slide.user.company) %></p>
            <p class="card-text"><small class="text-muted"><%= time_ago_in_words(job_slide.created_at) %> ago.</small></p>
          </div>
        </div>
        <% end %>
      <% else %>
        <div class="card mb-3 card-nen">
        <%= link_to image_tag('3.webp'), "#"%>
        <div class="card-body col-md-4 text-user">
          <h5 class="card-title card-text"><%= link_to "name Job","#" %></h5>
          <p class="card-text"><%= link_to "name company","#" %></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
      <div class="card mb-3 card-nen">
        <%= link_to image_tag('2.webp'), "#"%>
        <div class="card-body col-md-4 text-user">
          <h5 class="card-title card-text"><%= link_to "name Job","#" %></h5>
          <p class="card-text"><%= link_to "name company","#" %></p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<main>
  <div class="container">
    <div class="container-75">
      <div class="main-left col-md-4">
        <div class="row">
          <div class=" css-po">
            <div class="h3-filter">
              <h3><%= t("home.Filter") %> <%= link_to request.path, type: "button" do %>
             <i class="fa fa fa-refresh" id="back_home" aria-hidden="true"></i>
               <% end %></h3>
            </div>
             <%= search_form_for  @q ,url: root_path  do |f| %>
          <div class="form-group"><%= f.label t("home.title&area") %>
          <%= f.text_field :title_or_area_cont, class: 'form-control' , id: 'myJobs' %>
        </div>

        <div class="form-group"><%= f.label t("home.salary") %>
        <%= f.text_field :salary_gteq, class: 'form-control' %>
        </div>

        <%= f.submit t("home.search"), class: 'btn btn-primary' %>
        <% end %>
        <br>
        </div>
    </div>
  </div>
      <div class="main-right col-md-8">
        <div class="row">
          <div class="job-right">
            <div class="top col-md-12">
              <div class="row">
                <div class="col-md-3">
                  <p class="projects-count">

                  </p>
                </div>
                <div class="col-md-9">
                  <ul>
                    <% if !@approvedJobs.nil? %>
                      <li><%= link_to t("home.Newest"),home_path(type: "newest") ,class: "newest blue-a"%></li>
                    <% else %>
                      <li><%= link_to t("home.Newest"),home_path(type: "newest") ,class: "newest"%></li>
                    <% end %>
                    <% if !@job_Recommended.nil? %>
                    <li><%=link_to t("home.Recommended"),home_path(type: "recommended") ,class: "newest blue-a"%></li>
                    <% else %>
                    <li><%=link_to t("home.Recommended"),home_path(type: "recommended") ,class: "newest"%></li>
                    <% end %>
                  </ul>
                  <h4><%= t("home.sort") %></h4>
                </div>
              </div>
            </div>
            <% if params[:q] %>
              <div class="searchHome" >
                <% if !@jobs.nil? %>
                  <% @jobs.each do |job_new| %>
                    <div class="count-job col-md-12">
                      <div class="row">
                        <div class="img-job col-md-12">
                          <% if job_new.images.attached? %>
                            <%= link_to image_tag(job_new.images, class: "post-img"),job_path(job_new) %>
                          <% else %>
                            <%= link_to image_tag('no-image.jpg', class: "post-img"),job_path(job_new)%>
                          <% end %>
                        </div>
                        <div class="title-job col-md-12">
                          <%= link_to job_new.title,job_path(job_new) %></h5>
                        </div>
                        <div class="about-job col-md-12">
                           <p><%= job_new.what.html_safe.first(80) %>...</p>
                        </div>
                        <div class="name-company-job col-md-12">
                          <td> <%= link_to job_new.area, job_path(job_new) %> </td>
                        </div>
                        <div class="company-job col-md-12">
                      <div class="col-md-6">
                        <div class="row">
                          <% if job_new.user.company.images.attached? %>
                            <%= image_tag job_new.user.company.images.first , :style => " width: 50px; height: 50px; border-radius: 50px;" %>
                          <% else %>
                            <%= image_tag('no-image.jpg', :style => " width: 50px; height: 50px; border-radius: 50px;") %>
                          <% end %>
                          <%= link_to job_new.user.company.full_name, company_path(job_new.user.company) %>
                        </div>
                      </div>
                      <div class="col-md-6 ">
                        <div class="row text-right">
                          <%= job_new.salary %> $
                        </div>
                      </div>
                    </div>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                <h2><%= t("home.nojob") %></h2>
              <% end %>
              <% else %>
            <% if !@approvedJobs.nil? %>
              <% @approvedJobs.each do |job_new| %>
                <div class="count-job col-md-12">
                  <div class="row">
                    <div class="img-job col-md-12">
                        <% if job_new.images.attached? %>
                          <%= link_to image_tag(job_new.images, class: "post-img"),job_path(job_new) %>
                        <% else %>
                          <%= link_to image_tag('no-image.jpg', class: "post-img"),job_path(job_new)%>
                        <% end %>
                    </div>
                    <div class="title-job col-md-12">
                      <%= link_to job_new.title,job_path(job_new) %></h5>
                    </div>
                    <div class="about-job col-md-12">
                       <p><%= job_new.what.html_safe.first(80) %>...</p>
                      </div>
                    <div class="name-company-job col-md-12">
                         <td> <%= link_to job_new.area, job_path(job_new) %> </td>
                    </div>
                     <div class="company-job col-md-12">
                      <div class="col-md-6">
                        <div class="row">
                          <% if job_new.user.company.images.attached? %>
                            <%= image_tag job_new.user.company.images.first, :style => " width: 50px; height: 50px; border-radius: 50px;" %>
                          <% else %>
                            <%= image_tag('no-image.jpg', :style => " width: 50px; height: 50px; border-radius: 50px;") %>
                          <% end %>
                          <%= link_to job_new.user.company.full_name, company_path(job_new.user.company) %>
                        </div>
                      </div>
                      <div class="col-md-6 ">
                        <div class="row text-right">
                          <%= job_new.salary  %> $
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
              <%= paginate @approvedJobs, theme: 'twitter-bootstrap-3' %>
              <% elsif !@job_Recommended.nil? %>
              <% @job_Recommended.each do |recommended| %>
                <div class="count-job col-md-12">
                  <div class="row">
                    <div class="img-job col-md-12">
                        <% if recommended.images.attached? %>
                          <%= link_to image_tag(recommended.images, class: "post-img"),job_path(recommended) %>
                        <% else %>
                          <%= link_to image_tag('no-image.jpg', class: "post-img"),job_path(recommended)%>
                        <% end %>
                    </div>
                    <div class="title-job col-md-12">
                      <%= link_to recommended.title,job_path(recommended) %></h5>
                    </div>
                    <div class="about-job col-md-12">
                      <p><%= recommended.what.first(80) %>...</p>
                      </div>
                    <div class="name-company-job col-md-12">
                         <td> <%= link_to recommended.area, job_path(recommended) %> </td>
                    </div>
                    <div class="company-job col-md-12">
                      <div class="col-md-6">
                        <div class="row">
                          <% if recommended.user.company.images.attached? %>
                            <%= image_tag recommended.user.company.images.first, :style => "margin-top: 10px width: 50px; height: 50px; border-radius: 50px;" %>
                          <% else %>
                            <%= image_tag('no-image.jpg', :style => " width: 50px; height: 50px; border-radius: 50px;") %>
                          <% end %>
                          <%= link_to recommended.user.company.full_name, company_path(recommended.user.company) %>
                        </div>
                      </div>
                      <div class="col-md-6 ">
                        <div class="row text-right">
                          <%= recommended.salary %> $
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
              <%= paginate @job_Recommended, theme: 'twitter-bootstrap-3' %>
              <% else %>
                <h2><%= t("home.nojob") %></h2>
              <% end %>
              <% end %>
            </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</main>
<div>

</div>
<script type="text/javascript">
  $('.slider').slick({
  centerMode: true,
  centerPadding: '110px',
  adaptiveHeight:true,
  slidesToShow: 1,
  arrows:true,
  autoplay: true,
  autoplaySpeed :3000,
  responsive: [
    {
     breakpoint : 768,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 3
      }
    },
    {
      breakpoint: 480,
      settings: {
        arrows: false,
        centerMode: true,
        centerPadding: '40px',
        slidesToShow: 1
      }
    }
  ]
});
</script>

<script type="text/javascript">
  $('#myJobs').autocomplete({
    source: function (request, response) {
      $.ajax({
        url: "/home",
        data: { q:{title_or_area_cont: request.term }},
        dataType: 'json',
        success: function (data) {
          response($.map(data, function (dataItem) {
            return {data: dataItem.id, value: dataItem.title + dataItem.area };
          }));
        },
      });
    },
    select: function(event, ui) {
      window.location.assign('http://localhost:3000/jobs/' + ui.item.data);
    },
  });

  jQuery(document).ready(function(){
    window.onscroll = function() {
      var a = $(document).height() - 855;
      if (window.pageYOffset >= 544 && window.pageYOffset < a){
        jQuery('.css-po').css({position: 'fixed', top: '0px',width: '285px' });
      }
      else if(window.pageYOffset >= a) {
        jQuery('.css-po').css({position: 'absolute', top: 'auto'});
      }
      else
      {
        jQuery('.css-po').css({position: '', right: '', top: ''});

      }
    }
  });
</script>