config/routes.rb
Rails.application.routes.draw do
  namespace :employer do
    get 'bookmarks/index'
  end
  namespace :employer do
    get 'application/index'
  end
  namespace :employer do
    get 'payment/new'
  end
  resources :news
  resources :places
  devise_for :users,
                path: '',
                path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
                controllers: {omniauth_callbacks: 'omniauth_callbacks' }
    as :user do
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
    end


    scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # mount Sidekiq::Web => "/sidekiq"

    get 'companies/show'
    mount Ckeditor::Engine => '/ckeditor'
    root to: 'static_pages#home'
    resources :jobs
    get 'users/new'
    get 'static_pages/home',to: "home#jobs"
    get '/home', to: 'static_pages#home'
    get '/contact', to: 'static_pages#contact'
    get '/all', to: 'static_pages#products'
    get 'search', to: 'search#index'
    namespace :admin do
      root "admin#index"
    end

    resources :jobs do
      resources :applyjobs, only: [:create, :destroy]
    end
    resources :jobs do
      resources :bookmarks, only: [:create, :destroy]
    end

    resources :jobs
    resources :cvs
    resources :companies, only: [:show]
    resources :profiles
    resources :experiences
    resources :rooms
    resources :companies do
      resources :jobs, only: [:index]
    end
    resources :educations
    resources :users do
      resources :applyjobs

    end

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

    resources :users do

      resources :bookmarks
    end

    resources :experiences
    resources :cv_skills
    resources :cv_languages
    namespace :employer do
      resources :jobs do
        resources :applyjobs
      end
      resources :jobs do
        resources :bookmarks
      end
      resources :profiles
      resources :webhooks
      resources :bookmarks, only: [:index]
      resources :companies
      resources :payments
      resources :applications, only: [:index]
      resources :members
      resources :users
      resources :portal_sessions, only: [:create]

    end
    resources :portfolios
    resources :search do
      collection do
        get :autocomplete
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params["type"].nil?
      @cvs = Cv.search params["query"], operator: "or", page: params[:page], per_page: 5
      @companies = Company.search params["query"], operator: "or", suggest: true, page: params[:page], per_page: 5
    elsif params["type"]=="company"
      @companies = Company.search params["query"], operator: "or", suggest: true, page: params[:page], per_page: 5
    elsif params["type"]=="profile"
      @cvs = Cv.search params["query"], operator: "or", page: params[:page], per_page: 5
    end
  end

  def autocomplete
    render json:
    Company.search(params["term"], {
      fields: ["full_name"],
      match: :word_start,
      limit: 5
      }).map(&:full_name)+
    User.search(params["term"], {
      fields: ["fullname"],
      match: :word_start,
      limit: 5
      }).map(&:fullname)
  end
end

app/views/search/_all.html.erb
<% if @companies.suggestions.present? %>
  <div class="count-job search__suggest col-md-12">
    <%= t("search.Did you mean") %>
    "<%= link_to @companies.suggestions.first, search_path(query: @companies.suggestions) %>" ?
  </div>
<% end %>
<% if !@cvs.nil? && !@companies.nil? %>
  <div class="count-job col-md-12">
    <h4 class="count__total">
      <%= @companies.total_count + @cvs.total_count %> <%= t("search.results for") %>
        <% if @companies.suggestions.present? %>
          "<%= @companies.suggestions.first %>"
        <% else %>
          <%= params['query'] %>
        <% end %>
  	</h4>
  </div>
<% end %>
<% if !@companies.nil? %>
  <div class="count-job search__count col-md-12">
    <%= @companies.total_count %> <%= t("search.Companies") %>
  </div>
  <% @companies.each do |company| %>
    <%= link_to company_path(company), :action => 'go' do %>
      <div class="count-job search__company col-md-12">
        <div class="left-part col-md-1">
          <div class="row">
            <% if Company.find(company.id).images.attached? %>
              <%= image_tag Company.find(company.id).images.first, :style => "margin-top: 10px; width: 50px; height: 50px; border-radius: 50px;" %>
            <% else %>
              <%= image_tag('no-image.jpg', :style => "margin-top: 20px; width: 50px; height: 50px; border-radius: 50px;") %>
            <% end %>
          </div>
        </div>
        <div class="right-part col-md-11">
          <div class="row">
            <h4 class="search_com_name">
              <%= company.full_name %>
            </h4>
            <p class="search_com_add"><%= company.address %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= paginate @companies, theme: 'twitter-bootstrap-3' %>
<% end %>
<% if !@cvs.nil? %>
  <div class="count-job search__count col-md-12">
    <%= @cvs.total_count %> <%= t("search.Profiles") %>
  </div>
  <% @cvs.each do |cv| %>
    <%= link_to profile_path(cv.user), :action => 'go' do %>
      <div class="count-job search__company col-md-12">
        <div class="left-part col-md-1">
          <div class="row">
            <% if User.find(cv.user_id).image.attached? %>
              <%= image_tag User.find(cv.user_id).image, :style => "margin-top: 20px; width: 50px; height: 50px; border-radius: 50px;" %>
          <% else %>
              <%= image_tag('no-image.jpg', :style => "margin-top: 20px; width: 50px; height: 50px; border-radius: 50px;") %>
            <% end %>
          </div>
        </div>
        <div class="right-part col-md-11">
          <div class="row">
            <h4 class="search_cv_name">
              <%= cv.user.fullname %>
            </h4>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= paginate @cvs, theme: 'twitter-bootstrap-3' %>
<% end %>

app/views/search/index.html.erb
<div class="search__container">
  <div class="grid">
    <div class="grid__row">
      <div class="grid__column-3">
        <nav class="search">
          <h4 class="search__heading"><%= t("search.Search") %></h4>
          <ul class="search-list">
            <li class="search-item search-item--active">
              <%= link_to t("search.All"), search_path(query: params['query']), class: "search-item__link" %>
            </li>
            <li class="search-item">
              <%= link_to t("search.Companies"), search_path(type: "company", query: params['query']), class: "search-item__link" %>
            </li>
            <li class="search-item">
              <%= link_to t("search.Profiles"), search_path(type: "profile", query: params['query']), class: "search-item__link" %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="grid__column-9 search__all">
        <%= render 'all' %>
      </div>
    </div>
  </div>
</div>