config/routes.rb
Rails.application.routes.draw do
  namespace :employer do
    get 'bookmarks/index'
  end
  namespace :employer do
    get 'application/index'
  end
  namespace :employer do
    get 'payment/new'
  end
  resources :news
  resources :places
  devise_for :users,
                path: '',
                path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
                controllers: {omniauth_callbacks: 'omniauth_callbacks' }
    as :user do
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
    end


    scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # mount Sidekiq::Web => "/sidekiq"

    get 'companies/show'
    mount Ckeditor::Engine => '/ckeditor'
    root to: 'static_pages#home'
    resources :jobs
    get 'users/new'
    get 'static_pages/home',to: "home#jobs"
    get '/home', to: 'static_pages#home'
    get '/contact', to: 'static_pages#contact'
    get '/all', to: 'static_pages#products'
    get 'search', to: 'search#index'
    namespace :admin do
      root "admin#index"
    end

    resources :jobs do
      resources :applyjobs, only: [:create, :destroy]
    end
    resources :jobs do
      resources :bookmarks, only: [:create, :destroy]
    end

    resources :jobs
    resources :cvs
    resources :companies, only: [:show]
    resources :profiles
    resources :experiences
    resources :rooms
    resources :companies do
      resources :jobs, only: [:index]
    end
    resources :educations
    resources :users do
      resources :applyjobs

    end

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

    resources :users do

      resources :bookmarks
    end

    resources :experiences
    resources :cv_skills
    resources :cv_languages
    namespace :employer do
      resources :jobs do
        resources :applyjobs
      end
      resources :jobs do
        resources :bookmarks
      end
      resources :profiles
      resources :webhooks
      resources :bookmarks, only: [:index]
      resources :companies
      resources :payments
      resources :applications, only: [:index]
      resources :members
      resources :users
      resources :portal_sessions, only: [:create]

    end
    resources :portfolios
    resources :search do
      collection do
        get :autocomplete
      end
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  searchkick word_start: [:full_name], suggest: [:full_name]
  has_many :jobs
  belongs_to :user, optional: true
  has_many :members, dependent: :destroy
  has_many :users, through: :members, source: :user
  has_one :payment
  has_many_attached :images, dependent: :destroy
  validates :images,content_type: { in: %w[image/jpeg image/gif image/png],
             message: "must be a valid image format" },
             size:{ less_than: 5.megabytes, message: "should be less than 5MB" }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: true
  validates :full_name, :address, :phone, :link, :total, presence: true
  validates :descr, presence: true, length: { minimum: 30 }
  def search_data
     as_json only: [:full_name, :address, :link]
    {
      full_name: full_name,
      address: address,
      link: link
    }
  end

  included do
    acts_as_url :full_name, url_attribute: :full_name, sync: true
  end

  def to_param
    "#{id}/#{full_name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
  	@company = Company.find params[:id]
  	@jobs = @company.user.jobs.all_approved_true.limit(4)
  end
end

app/controllers/employer/companies_controller.rb
class Employer::CompaniesController < ApplicationController
  before_action :user_employer?
  before_action :return_home, only: [:index]
  before_action :return_payment, only: [:new, :show, :create, :edit, :update ]
  before_action :return_company, only: [:new]

  def new
    @company = Company.new
    @member = Member.new
    @user = User.new
  end

  def index
    @member = Member.all
    @jobs = current_user.jobs.limit(Settings.jobs)
    @prices = Stripe::Price.list(
      lookup_keys: ['starter', 'pro', 'enterprise'],
      expand: ['data.product']
    ).data.sort_by {|p| p.unit_amount}
  end

  def show
    @company = Company.find params[:id]
    @user_company = @company.users
    @member = Member.new
    @user = User.new
    @q = User.ransack params[:q]
    @users = @q.result(distinct: true).limit(5)
    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def create
    @company = Company.new company_params
    @company.user_id = current_user.id
    Stripe::Charge.create(
     :amount => 500,
     :currency => "usd",
     :source => params[:stripeToken],
     :description => "Charge for jenny.rosen@example.com"
    )
    if @company.save
      redirect_to employer_company_path(@company)
    end
  end

  def edit
    @company = Company.find params[:id]
  end

  def update
    @company = Company.find params[:id]
    if @company.update company_params
      redirect_to employer_company_path
    end
  end

  def destroy
    @company = Company.find params[:id]
    if @company.destroy
      redirect_to  employer_company_path
    end
  end

  private

  def company_params
     params.require(:company).permit(:full_name, :address, :phone, :link,:map,
      :total, :email, :descr, :user_ids => [], images: [])
  end

  def return_payment
    unless !current_user.company.payment.nil? && !current_user.company.payment.stripe_customer_id.nil?
      flash[:danger] = "Please payment."
    redirect_to employer_companies_url
    end
  end

  def return_company
    if !current_user.company.nil?
      redirect_to employer_companies_url
    end
  end

  def return_home
    unless !current_user.employer_role.nil?
      redirect_to root_path
    end
  end
end

app/controllers/employers/companies_controller.rb
class Employers::CompaniesController < ApplicationController
  before_action :authenticate_user!

  def new
    @company = Company.new
  end

  def index
    @jobs = current_user.jobs.limit(Settings.jobs)
  end

  def show
    @company = Company.find params[:id]
  end

  def create
    @company = Company.new company_params
    @company.user = current_user
    @company.image.attach(params[:company][:image])
    if @company.save
      redirect_to employers_company_path(@company)
    end
  end

  def edit
    @company = Company.find params[:id]
  end

  def update
    @company = Company.find params[:id]
    if @company.update company_params
      redirect_to employers_company_path
    end
  end

  private

  def company_params
     params.require(:company).permit(:full_name, :address, :phone, :link, :total, :email, :descr, :image)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/show.html.erb
<div class="container">
    <div>
        <div class="dis">
            <%= link_to company_path(params[:id]) do %>
            <% if @company.images.attached? %>
            <%=  image_tag(@company.images.first, :style => "width: 50px; height: 50px; border-radius: 50%;", class: "post-img") %>
            <% else %>
            <%=  image_tag('no-image.jpg', :style => "width: 50px; height: 50px; border-radius: 50%;", class: "post-img")%>
            <% end %>
            <% end %>
            <div class="name_company">
                <%= @company.full_name %>
                <div>
                    <%= @company.email %>
                </div>
            </div>
            <div class="nav_company">
                <div><a href="#">
                        <%= t("global.job.home") %></a></div>
                <div>
                    <%= link_to t("global.job.jobs"), company_jobs_path(@company) %>
                </div>
            </div>
        </div>
        <div>
            <% if @company.images.attached? %>
            <%= image_tag @company.images.first, :style => "width: 100%; height: 400px" %>
            <% else %>
            <%= image_tag('no-image.jpg', :style => "width: 100%; height: 400px") %>
            <% end %>
        </div>
        <div class="container">
            <div class="col-md-2"></div>
            <div class="col-md-7">
                <h1>
                    <%= t("global.job.about") %>
                </h1>
                <div class="descr_company">
                    <%= @company.descr.html_safe %>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="ml_2">
        <h1>
            <%= t("global.job.company") %>
        </h1>
        <div class="info_company">
            <%= link_to company_path(params[:id]) do %>
            <% if @company.images.attached? %>
            <%=  image_tag(@company.images.first, :style => "width: 50px; height: 50px; border-radius: 50%;", class: "post-img") %>
            <% else %>
            <%=  image_tag('no-image.jpg', :style => "width: 50px; height: 50px; border-radius: 50%;", class: "post-img")%>
            <% end %>
            <% end %>
            <span>
                <%= @company.full_name%></span>
            <div><i class="fa fa-map-marker fa-2x" aria-hidden="true"></i> <span>
                    <%= @company.address%></span></div>
            <div><i class="fa fa-link fa-2x" aria-hidden="true"></i> <span>
                <% if @company.link %>
                    <%= link_to @company.link.first(80) + "..."%></span></div>
                    <% end %>
            <div><i class="fa fa-users fa-2x" aria-hidden="true"></i> <span>
                    <%= @company.total%></span></div>
            <div><i class="fa fa-envelope-o fa-2x" aria-hidden="true"></i> <span>
                    <%= @company.email %></span></div>
        </div>
    </div>
    <div class="ml_2">
        <h1>
            <%= t("global.job.jobs") %>
        </h1>
        <div class="jobs_company">
            <% @jobs.each do |job| %>
            <div class="col-md-3">
                <%= link_to job_path(job) do %>
                <% if job.images.attached? %>
                <%=  image_tag(job.images, style: "width: 100%; height: 150px;", class: "post-img") %>
                <% else %>
                <%=  image_tag('no-image.jpg', style: "width: 100%; height: 150px;", class: "post-img")%>
                <% end %>
                <h4>
                    <%= job.title %>
                </h4>
                <% end %>
            </div>
            <% end %>
            <div class="col-md-12 text-center">
                <hr>
                <%= link_to "More",company_jobs_path(@company) %>
            </div>
        </div>
    </div>
</div>