config/routes.rb
Rails.application.routes.draw do
  namespace :employer do
    get 'bookmarks/index'
  end
  namespace :employer do
    get 'application/index'
  end
  namespace :employer do
    get 'payment/new'
  end
  resources :news
  resources :places
  devise_for :users,
                path: '',
                path_names: {sign_in: 'login' ,sign_out: 'logout' ,edit: 'profile',sign_up: 'resgistration'},
                controllers: {omniauth_callbacks: 'omniauth_callbacks' }
    as :user do
      get "signin", to: "devise/sessions#new"
      post "signin", to: "devise/sessions#create"
      delete "signout", to: "devise/sessions#destroy"
    end


    scope "(:locale)", locale: /en|vi/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # mount Sidekiq::Web => "/sidekiq"

    get 'companies/show'
    mount Ckeditor::Engine => '/ckeditor'
    root to: 'static_pages#home'
    resources :jobs
    get 'users/new'
    get 'static_pages/home',to: "home#jobs"
    get '/home', to: 'static_pages#home'
    get '/contact', to: 'static_pages#contact'
    get '/all', to: 'static_pages#products'
    get 'search', to: 'search#index'
    namespace :admin do
      root "admin#index"
    end

    resources :jobs do
      resources :applyjobs, only: [:create, :destroy]
    end
    resources :jobs do
      resources :bookmarks, only: [:create, :destroy]
    end

    resources :jobs
    resources :cvs
    resources :companies, only: [:show]
    resources :profiles
    resources :experiences
    resources :rooms
    resources :companies do
      resources :jobs, only: [:index]
    end
    resources :educations
    resources :users do
      resources :applyjobs

    end

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]

    resources :users do

      resources :bookmarks
    end

    resources :experiences
    resources :cv_skills
    resources :cv_languages
    namespace :employer do
      resources :jobs do
        resources :applyjobs
      end
      resources :jobs do
        resources :bookmarks
      end
      resources :profiles
      resources :webhooks
      resources :bookmarks, only: [:index]
      resources :companies
      resources :payments
      resources :applications, only: [:index]
      resources :members
      resources :users
      resources :portal_sessions, only: [:create]

    end
    resources :portfolios
    resources :search do
      collection do
        get :autocomplete
      end
    end
  end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :cv
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def index
    @education = Education.new
    @educations = current_user.cv.educations
  end

  def new
    @education = Education.new
    @educations = current_user.cv.educations
    respond_to do |format|
      format.html{render(partial:"education_form")}
    end

  def show
    @user = User.find params[:id]
    @education = Education.new
    @educations = @user.cv.educations
  end

  end

  def create
    @education = current_user.cv.educations.build education_params
    if @education.save
      @educations = current_user.cv.educations
      @education = Education.new
      respond_to do |format|
        format.html{render(partial:"education_section")}
      end
    end
  end

  def edit
    @education = Education.find params[:id]
    respond_to do |format|
      format.html{render(partial:"education_form")}
    end
  end

  def update
    @education = Education.find params[:id]
    if @education.update education_params
      @education = Education.new
      @educations = current_user.cv.educations
      respond_to do |format|
        format.html{render(partial:"education_section")}
        format.json
      end
    end
  end

  def destroy
    @education = Education.find params[:id]
    if @education.destroy
      respond_to do |format|
        format.json{render json: {result: 'OK'}}
      end
    end
  end

private

  def education_params
    params.require(:education).permit(:yearschool, :degree, :school, :status)
  end
end

app/views/educations/_education.html.erb
<div class="edu_list_form" id="education-<%= education.id %>">
  <div id="edu_school">
    <b><%=t("ed.school")%>:</b><%= education.school %>
  </div>
  <div id="edu_degree" >
    <b><%=t("ed.degree")%>:</b><%= education.degree %>
  </div>
  <div id="edu_yearschool">
    <b><%=t("ed.graduation")%>:</b><%= education.yearschool %>
  </div>
  <div id="edu_descr">
    <b><%=t("ed.descr")%>:</b><%= education.status %>
  </div>
  <div class="edit_delete_button">
    <%= link_to t("ed.edit"), edit_education_path(education),
      class: "btn btn-primary edit-education","data-id": education.id %>
    <%= link_to t("ed.delete"), education_path(education),
      class: "btn btn-outline-secondary destroy","data-id": education.id %>
  </div>
</div>
<script type="text/javascript">
  $("#education-<%= education.id %> .destroy").on('click', function(event) {
    event.preventDefault();
    var id = $(this).data('id');
    $.ajax({
      url: $(this).attr('href'),
      method: 'DELETE',
      dataType: 'JSON',
      data: $(this).serialize(),
      success: function(data) {
        if (data.result == 'OK') {
          $('#education-' + id).remove();
        }
      }
    });
  });
</script>

app/views/educations/_education_form.html.erb
<div class="form_education">
  <div class="form-education ">
    <%= form_for @education  do |f| %>
    <div class="form-group">
      <%= f.label t("ed.school") %>
      <%= f.text_field :school ,placeholder: "",class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label t("ed.degree") %>
      <%= f.text_field :degree ,placeholder: "",class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label t("ed.graduation") %>
      <%= f.date_field :yearschool ,placeholder: ""  %>
    </div>
    <div class="form-group">
      <%= f.label t("ed.descr") %>
      <%= f.text_field :status  ,placeholder: "",class: "form-control" %>
    </div>
    <div class="submit-education">
      <input class="btn btn-danger cancel" type="button" value='<%= t("ed.cancel") %>'>
      <%= f.submit t("ed.update"), class: "btn btn-genos"%>
    </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(".form_education form .cancel").on('click', function() {
    $(".form_education").remove();
    $('[id^="education"]').show();
  });

  $(".form-education form").on('submit', function(event) {
    event.preventDefault();
    var formHTML = event.target;
    $.ajax({
      url: formHTML.action,
      method: 'POST',
      data: $(this).serialize(),
      success: function(data) {
        $('#education_section').html(data);
        }
    });
  });
</script>

app/views/educations/_education_section.html.erb
<div id="education">
  <input type="button" class="btn btn-outline-secondary add" id="edu_add_button" value=" ✚ ">
</div>
<div id="educations">
  <%= render @educations %>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.form_educatin').hide();
    $('#education .add').on('click', function(event) {
      event.preventDefault();
      $('.form_education').remove();
      $.ajax({
        url: '<%= new_education_path %>',
        method: 'GET',
        success: function(data) {
          $('#education').append(data);
        }
      });
    });
    $('#educations .edit-education').on('click', function(event) {
      var id = $(this).data('id');
      event.preventDefault();
      $('[id^="education"]').show();
      $('#education-' + id).hide();
      $('.form_education').remove();
      $.ajax({
        url: $(this).attr('href'),
        method: 'GET',
        success: function(data) {
          $('#education-' + id).before(data);
        }
      });
    });
  });
</script>

app/views/educations/_profile_education.html.erb
<% if !@educations.nil? %>
  <% @educations.each do |education| %>
  <div class="edu_list_form" >
		  <div id="edu_school">
		    <b><%=t("ed.school")%>:</b><%= education.school %>
		  </div>
		  <div id="edu_degree" >
		    <b><%=t("ed.degree")%>:</b><%= education.degree %>
		  </div>
		  <div id="edu_yearschool">
		    <b><%=t("ed.graduation")%>:</b><%= education.yearschool %>
		  </div>
		  <div id="edu_descr">
		    <b><%=t("ed.descr")%>:</b><%= education.status %>
		  </div>
	  </div>
  <% end %>
<% end %>

app/views/educations/index.html.erb
<div id="education_section">
    <%= render "education_section" %>
</div>

app/views/educations/new.html.erb
<div id="education_section">
    <%= render "education_section" %>
</div>